apiVersion: v1
kind: Service
metadata:
  name: sirenaix-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sirenaix-gateway
  ports:
    - name: https
      port: 443
      targetPort: https
